# Generated by Django 4.2.5 on 2023-09-12 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('teamCount', models.PositiveSmallIntegerField()),
                ('link', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('datetimeStart', models.DateTimeField(auto_now_add=True)),
                ('timer', models.TimeField()),
                ('timerIsActive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pincode', models.PositiveSmallIntegerField()),
                ('userCount', models.PositiveSmallIntegerField()),
                ('sessionID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team', to='app.session')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='statusID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session', to='app.statussession'),
        ),
    ]
